- hosts: webservers
  vars:
    users:
      - perdejnik
      - kalich
  tasks:
    - name: add users
      ansible.builtin.user:
        name: "{{ item }}"
      loop: "{{ users }}"
    
    - name: git install
      ansible.builtin.apt:
        name: git
        state: latest
      become: yes

    - name: create .ssh
      ansible.builtin.file:
        path: "/home/{{ item }}/.ssh"
        state: directory
      loop: "{{ users }}"

    - name: copy pub_key
      ansible.builtin.copy:
        src: files/authorized_keys
        dest: "/home/{{ item }}/.ssh/authorized_keys"
      loop: "{{ users }}"

    - name: clone rep
      ansible.builtin.git:
        repo: "https://github.com/nnenemoy/scripts.git"
        dest: "/home/{{ item }}/kaki"
        version: main
      loop: "{{ users }}"
      when: item != "kalich"

    - name: update .gitconfig
      ansible.builtin.template:
        src: templates/.gitconfig.j2
        dest: "/home/{{ item }}/.gitconfig"
      loop: "{{ users }}"
      when: item != "kalich"
