- hosts: appservers
  tasks:
    - name: apt cache update
      ansible.builtin.apt:
        update_cache: true
      become: yes
      tags: updaptcache

    - name: install soft
      ansible.builtin.apt:
        name:
          - git
          - make
          - nodejs
        state: present
      become: yes
      tags: softinst

    - name: user create
      ansible.builtin.user:
        name:
          - kal
          - kalivan
          - kalivanich
        state: present
      become: yes
      tags: usercr

    - name: remove soft
      ansible.builtin.apt:
        name:
          - git
          - make
          - nodejs
        state: absent
      become: yes
      tags: softrem
